/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : Aircooler.c
*  Description  : Main Program
*  Creation Date: 2024-08-17
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "aircooler.h"
int main (void);

volatile uint32_t time_us = 0;
volatile uint32_t count;
volatile uint32_t data[32];



int main(void)
{
	EI();
	uint32_t lastCmdTime = 0,currentTime;

	R_Config_PORT_Create();
	R_Config_UART0_Create();
	R_Config_UART0_Start();
	R_Config_INTC_INTP8_Start();
	Timer_Init();
	resetpins();
	print(" Start ");

	 while(1)
	 {
		 while(1)
		 {
			 readModePin();
			 readSpeedPin();
			 if(count!=0)
				 break;
		 }
		 lastCmdTime=Get_Current_Time_us();
		 while(1)
		 {
			 currentTime=Get_Current_Time_us();
			 if((currentTime-lastCmdTime) > (RC5CMD_DURATION))
			 {
				 count=0;
				 break;
			 }
			 if(count >=  PULSECOUNT)
			 {
				 R_Config_INTC_INTP8_Stop();
				 processData();
				 R_BSP_SoftwareDelay(100,BSP_DELAY_MILLISECS);
				 count = 0;
				 R_Config_INTC_INTP8_Start();
				 break;
			 }
		 }
	 }
}
