/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : RL78_G16_CapTouch.c
*  Description  : Main Program
*  Creation Date: 2024-08-30
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include<string.h>
void qe_touch_main(void);
int main (void);
void Task1(void);
void Task2(void);

void uart_integer(int);
extern volatile uint8_t * gp_uart1_rx_address;    /* uart1 receive buffer address */
extern volatile uint16_t g_uart1_rx_count;        /* uart1 receive data number */
extern uint16_t g_uart1_rx_length;

extern struct ChimneyState
{
	unsigned char micstatus:1;
	unsigned char gasleakstatus:1;
	unsigned char modestatus:1;
	unsigned char autocleanstatus:1;
	unsigned char lightstatus:1;
	unsigned char speedstatus:2;
	unsigned char powerstatus:1;
};

extern struct Cmdpacket
{
	unsigned char Header;
	unsigned char Src;
	struct ChimneyState chimney;
	unsigned char checksum;
}Renesaspack;

extern void Button_Action(unsigned int);
extern void Receive_Action(void);

__saddr unsigned int g_pulse_width[4];    /* Store pulse width */
unsigned char g_times;   /* Measurement times counter */

__saddr unsigned int g_pulse_width1[4];    /* Store pulse width */
unsigned char g_times1;   /* Measurement times counter */

extern unsigned char rcvflag;
extern unsigned char sendflag;
unsigned char global_data[4];


extern unsigned char rcvpack[4];

//extern unsigned char comvar;
//extern unsigned char confirmed;
//extern unsigned char leftDetected;
//extern unsigned char rightDetected;


uint8_t var=' ';
uint32_t pulse_width;

int main(void)
{
    R_Config_UART1_Create();
	R_Config_UART1_Start();
	R_Config_UART2_Create();
	R_Config_UART2_Start();
	R_Config_TAU0_2_Create();
	R_Config_TAU0_2_Start();
	R_Config_TAU0_3_Create();
	R_Config_TAU0_3_Start();
	R_Config_TAU0_0_Create();
	R_Config_TAU0_0_Start();
	R_Config_TAU0_1_Create();
	R_Config_TAU0_4_Create();
	gp_uart1_rx_address = rcvpack;
	g_uart1_rx_count=0;
	g_uart1_rx_length=4;
	g_times = 4U;
	g_times1 = 4U;
	memset(&Renesaspack.chimney,0,sizeof(Renesaspack.chimney));
    EI();
    qe_touch_main();
    while(1)
    {
    	HALT();
    }
    //return 0;
}

void uart_integer(int num)
{
	char arr[10];
	int i=0;
	while(num)
	{
		arr[i]=(num%10)+48;
		num/=10;
		i++;
	}
	for(i--;i>=0;i--)
	{
		R_Config_UART2_Send(arr+i,1);
		R_BSP_SoftwareDelay(100,BSP_DELAY_MILLISECS);
	}
	//R_BSP_SoftwareDelay(20,BSP_DELAY_MILLISECS);
	R_Config_UART2_Send(&var,1);
}

void Task1(void)
{



}

void Task2(void)
{

	if(rcvflag==1)
	{
		rcvflag=0;
		PIN_WRITE(1,2)=~PIN_READ(1,2);
		memmove(&global_data,&rcvpack,4);
		gp_uart1_rx_address = rcvpack;
		memset(&rcvpack,'\0',4);
	    g_uart1_rx_count=0;
		g_uart1_rx_length=4;
		Receive_Action();
	}

}

//extern __saddr unsigned int g_pulse_width[8];    /* Store pulse width */
//extern unsigned char g_times;                      /* Measurement times counter */
//g_pulse_width[8U - g_times] = g_tau0_ch0_width;    /* Store capture value */
//
//   if (0U == ( --g_times))        /* 8 times measurement finished ? */
//   {
//       R_Config_TAU0_0_Stop();    /* Stops timer counter */
//   }
